[pkgs]
packages = ["php", "php-fpm", "nginx"]

[phases.setup]
nixPkgsArchive = "https://nixos.org/channels/nixos-23.05"

[phases.build]
cmds = [
    "composer install --no-dev --optimize-autoloader"
]

[phases.start]
cmds = [
    "php-fpm --nodaemonize --fpm-config /etc/php-fpm.conf &",
    "nginx -g 'daemon off;'"
]
