[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "cp php-fpm.conf /etc/php-fpm.conf"
]

[phases.start]
cmds = [
  "php-fpm --nodaemonize --fpm-config /etc/php-fpm.conf &",
  "nginx -g 'daemon off;'"
]
