services:
  app:
    build: .
    container_name: laravel_app
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    expose:
      - "80"
    ports:
      - "80:80"  # Expose Nginx inside this container
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: tajms_db
      MYSQL_USER: tajms_user
      MYSQL_PASSWORD: tajms_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
